name: Fetch npm tarballs
on:
  workflow_dispatch:
  push:
    branches-ignore: ['bot/**']
    paths:
      - 'methodologies/**'
      - 'schemas/**'
      - 'tools/**'
  pull_request:
    branches:
      - 'main'
      - 'feat/**'
    paths:
      - 'methodologies/**'
      - 'schemas/**'
      - 'tools/**'
jobs:
  pack:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !startsWith(github.ref_name, 'bot/') &&
      !(github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'bot/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          clean: true
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.11.1'
      - run: |
          mkdir -p out
          npm pack fast-deep-equal@3.1.3 --pack-destination out
          npm pack json-schema-traverse@1.0.0 --pack-destination out
          npm pack uri-js@4.4.1 --pack-destination out
          npm pack require-from-string@2.0.2 --pack-destination out
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: npm-tarballs
          path: out/*.tgz
